CREATE TYPE "reciepent" AS ENUM('customer', 'courier', 'outlet');--> statement-breakpoint
CREATE TYPE "state" AS ENUM('addToChart', 'checkout');--> statement-breakpoint
CREATE TYPE "vechile_type" AS ENUM('car', 'motorcycle');--> statement-breakpoint
CREATE TABLE "couriers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "couriers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"avatar" varchar(255) DEFAULT 'avatar-courier.png' NOT NULL,
	"vehicle_plate" varchar(255) NOT NULL,
	"vehicle_type" "vechile_type" NOT NULL,
	"ratings" varchar DEFAULT '5',
	"updated_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "customers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "customers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"ratings" varchar DEFAULT '5',
	"updated_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "orderDetails" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "orderDetails_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"order_id" uuid NOT NULL,
	"product_id" uuid NOT NULL,
	"quantity" integer NOT NULL,
	"note_product" varchar(255) NOT NULL,
	"extra" json,
	"summary_price" varchar(10) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"status" "state"
);
--> statement-breakpoint
CREATE TABLE "orders" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"costomer_id" integer NOT NULL,
	"courier_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "outlets" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "outlets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"address" varchar(255) NOT NULL,
	"phone" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL UNIQUE,
	"user_id" uuid NOT NULL,
	"avatar" varchar(255) DEFAULT 'avatar.png' NOT NULL,
	"ratings" varchar DEFAULT '5',
	"updated_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "products" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"product_name" varchar(255) NOT NULL,
	"price" varchar(10) NOT NULL,
	"price_mark_down" varchar(10) NOT NULL,
	"outlet_id" integer NOT NULL,
	"ratings" varchar DEFAULT '5',
	"updated_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "ratings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"orderDetailsTable" integer NOT NULL,
	"ratings" varchar DEFAULT '5',
	"reviewer" uuid NOT NULL,
	"reciepent" uuid NOT NULL,
	"reciepent_as" "reciepent",
	"updated_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"name" varchar(255) NOT NULL,
	"phone" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL UNIQUE,
	"address" varchar(255) NOT NULL,
	"updated_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "couriers" ADD CONSTRAINT "couriers_user_id_users_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id");--> statement-breakpoint
ALTER TABLE "customers" ADD CONSTRAINT "customers_user_id_users_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id");--> statement-breakpoint
ALTER TABLE "orderDetails" ADD CONSTRAINT "orderDetails_order_id_orders_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id");--> statement-breakpoint
ALTER TABLE "orderDetails" ADD CONSTRAINT "orderDetails_product_id_products_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id");--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_costomer_id_customers_id_fkey" FOREIGN KEY ("costomer_id") REFERENCES "customers"("id");--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_courier_id_couriers_id_fkey" FOREIGN KEY ("courier_id") REFERENCES "couriers"("id");--> statement-breakpoint
ALTER TABLE "outlets" ADD CONSTRAINT "outlets_user_id_users_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id");--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_outlet_id_outlets_id_fkey" FOREIGN KEY ("outlet_id") REFERENCES "outlets"("id");--> statement-breakpoint
ALTER TABLE "ratings" ADD CONSTRAINT "ratings_orderDetailsTable_orderDetails_id_fkey" FOREIGN KEY ("orderDetailsTable") REFERENCES "orderDetails"("id");--> statement-breakpoint
ALTER TABLE "ratings" ADD CONSTRAINT "ratings_reviewer_users_id_fkey" FOREIGN KEY ("reviewer") REFERENCES "users"("id");--> statement-breakpoint
ALTER TABLE "ratings" ADD CONSTRAINT "ratings_reciepent_users_id_fkey" FOREIGN KEY ("reciepent") REFERENCES "users"("id");