export const CATEGORY_IN = [
    "Penjualan produk/jasa",
    "Pembayaran piutang pelanggan",
    "Uang muka/down payment dari customer",
    "Pendapatan layanan tambahan",
    "Komisi atau fee",
    "Modal pribadi owner",
    "Tambahan setoran modal partner/investor",
    "Pinjaman bank",
    "Pinjaman keluarga/teman",
    "Dana hibah atau bantuan pemerintah",
    "Penjualan kendaraan operasional",
    "Penjualan mesin/peralatan",
    "Penjualan stok lama/scrap",
    "Lain-lain",
];

export const CATEGORY_OUT = [
    "Pembelian bahan baku",
    "Pembelian stok barang dagang",
    "Gaji karyawan",
    "Sewa tempat",
    "Listrik, air, internet",
    "Ongkos kirim",
    "Biaya packaging",
    "Biaya admin marketplace",
    "Iklan/marketing",
    "Transportasi operasional",
    "ATK dan perlengkapan kantor",
    "Maintenance/perbaikan kecil",
    "Cicilan Pinjaman",
    "Prive Owner (Uang Owner yang dipakai sebelumnya)",
    "Pengembalian modal investor",
    "Pengeluaran Darurat",
    "Biaya Notaris atau badan hukum",
    "Pembelian Mesin / Asset",
    "BPJS Karyawan",
    "Lain-lain",
];
