CREATE TYPE "public"."order_status" AS ENUM('pending', 'confirmed', 'preparing', 'on_delivery', 'delivered', 'cancelled');--> statement-breakpoint
CREATE TABLE "promos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "promos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(20) NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" varchar(500) NOT NULL,
	"discount_percent" integer NOT NULL,
	"min_order" integer DEFAULT 0 NOT NULL,
	"max_discount" integer,
	"valid_until" timestamp with time zone NOT NULL,
	"gradient" varchar(255) DEFAULT 'from-rose-500 to-pink-600' NOT NULL,
	"features" text[] DEFAULT '{}' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "promos_code_unique" UNIQUE("code")
);
--> statement-breakpoint
ALTER TABLE "orderDetails" ALTER COLUMN "note_product" SET DATA TYPE json USING "note_product"::json;--> statement-breakpoint
ALTER TABLE "orderDetails" ALTER COLUMN "note_product" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "orders" ALTER COLUMN "courier_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "outlet_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "status" "order_status" DEFAULT 'pending' NOT NULL;--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "promo_id" integer;--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "discount_amount" varchar(15);--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "delivery_fee" varchar(15);--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "scheduled_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "note" json;--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "updated_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "deleted_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "outlets" ADD COLUMN "lat" varchar(255) NOT NULL;--> statement-breakpoint
ALTER TABLE "outlets" ADD COLUMN "lon" varchar(255) NOT NULL;--> statement-breakpoint
ALTER TABLE "outlets" ADD COLUMN "review_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "outlets" ADD COLUMN "tags" text[] DEFAULT '{}' NOT NULL;--> statement-breakpoint
ALTER TABLE "outlets" ADD COLUMN "features" text[] DEFAULT '{}' NOT NULL;--> statement-breakpoint
ALTER TABLE "outlets" ADD COLUMN "is_open" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "features" text[] DEFAULT '{}' NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "is_recommended" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "discount_percent" integer;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "review_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_outlet_id_outlets_id_fk" FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_promo_id_promos_id_fk" FOREIGN KEY ("promo_id") REFERENCES "public"."promos"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "id_idx" ON "orders" USING btree ("id");--> statement-breakpoint
CREATE INDEX "costomer_id_idx" ON "orders" USING btree ("costomer_id");--> statement-breakpoint
CREATE INDEX "courier_id_idx" ON "orders" USING btree ("courier_id");--> statement-breakpoint
CREATE INDEX "outlet_id_idx" ON "orders" USING btree ("outlet_id");