CREATE TABLE "schedule_product_ads" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "schedule_product_ads_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"time_display" json
);
--> statement-breakpoint
ALTER TABLE "product_ads" ADD COLUMN "schedule_at_id" integer;--> statement-breakpoint
ALTER TABLE "product_ads" ADD CONSTRAINT "product_ads_schedule_at_id_schedule_product_ads_id_fk" FOREIGN KEY ("schedule_at_id") REFERENCES "public"."schedule_product_ads"("id") ON DELETE no action ON UPDATE no action;