CREATE TABLE "menu_groups" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "menu_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"outlet_id" integer NOT NULL,
	"name" varchar(60) NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "menu_group_id" integer;--> statement-breakpoint
ALTER TABLE "menu_groups" ADD CONSTRAINT "menu_groups_outlet_id_outlets_id_fk" FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "menu_groups_outlet_idx" ON "menu_groups" USING btree ("outlet_id","sort_order");--> statement-breakpoint
CREATE UNIQUE INDEX "menu_groups_outlet_name_uq" ON "menu_groups" USING btree ("outlet_id","name");--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_menu_group_id_menu_groups_id_fk" FOREIGN KEY ("menu_group_id") REFERENCES "public"."menu_groups"("id") ON DELETE set null ON UPDATE no action;