-- The area Ulun Pesan's couriers serve, as a centre point plus a radius.
--
-- Set by an admin on a map. Two things depend on it: the coverage visualisation
-- in the admin panel, and owner registration, which refuses an outlet whose
-- location falls outside the circle ("titik lokasi anda tidak tercakup dalam
-- area penjemputan kurir kami").
--
-- Straight-line radius on purpose. This answers the coarse question "do we
-- operate here at all", which an admin needs to be able to draw and reason
-- about. It is NOT the per-order delivery cap — that one is 50 km of ROAD
-- distance, enforced in orders/create, and the two are deliberately separate
-- concerns that happen to share a default number.
--
-- No row is seeded. An empty table means "not configured", and every caller
-- treats that as unrestricted rather than as a zero-radius blackout — otherwise
-- deploying this migration would lock out every new owner until an admin
-- happened to open the page.
--
-- numeric, not varchar: that is how '' and the literal text 'NaN' ended up in
-- coordinate columns before (see 0041 and the repair that preceded it).

CREATE TABLE IF NOT EXISTS "service_area" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "center_lat" numeric(10, 7) NOT NULL,
  "center_lon" numeric(10, 7) NOT NULL,
  "radius_km" integer DEFAULT 50 NOT NULL,
  "updated_by" text,
  "updated_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "service_area" ADD CONSTRAINT "service_area_updated_by_users_id_fk"
  FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
