-- Courier applications: the photos, and the admin verdict on them.
--
-- Hand-trimmed from `drizzle-kit generate`. The generator also re-emitted
-- service_area, outlets.courier_reachable, couriers.last_lat/lon and
-- users.phone_changed_at — all of which migrations 0044-0047 already applied —
-- because those were hand-written and their snapshots never caught up. Running
-- the generated file as-is would have died on "relation service_area already
-- exists" mid-deploy. The 0048 snapshot IS kept: it now reflects the real
-- database, so the next generate diffs from the truth.
--
-- IF NOT EXISTS / DO-block guards throughout, matching 0046-0047: this file has
-- to be safe to re-run against a database that already has part of it.

DO $$ BEGIN
  CREATE TYPE "public"."courier_verification_status" AS ENUM('pending', 'approved', 'rejected');
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "public"."courier_document_kind" AS ENUM('face_front', 'face_right', 'face_left', 'face_back', 'stnk', 'sim_c', 'vehicle_front', 'vehicle_right', 'vehicle_left', 'vehicle_back');
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint

-- One row per required slot. ON DELETE cascade: removing a courier removes
-- their ID photographs with them — this is the one table here holding a picture
-- of somebody's face and driving licence, and it must not outlive the account.
CREATE TABLE IF NOT EXISTS "courier_documents" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"courier_id" integer NOT NULL,
	"kind" "courier_document_kind" NOT NULL,
	"image" varchar(255) NOT NULL,
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "courier_documents" ADD CONSTRAINT "courier_documents_courier_id_couriers_id_fk"
    FOREIGN KEY ("courier_id") REFERENCES "public"."couriers"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint

-- Re-uploading an angle replaces it. An admin comparing a face against a SIM
-- must be looking at the current answer per slot, not a stack to date-sort.
CREATE UNIQUE INDEX IF NOT EXISTS "courier_documents_courier_kind_uq"
  ON "courier_documents" USING btree ("courier_id","kind");
--> statement-breakpoint

ALTER TABLE "couriers" ADD COLUMN IF NOT EXISTS "verification_status" "courier_verification_status" DEFAULT 'pending' NOT NULL;--> statement-breakpoint
ALTER TABLE "couriers" ADD COLUMN IF NOT EXISTS "verification_note" varchar(500);--> statement-breakpoint
ALTER TABLE "couriers" ADD COLUMN IF NOT EXISTS "verified_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "couriers" ADD COLUMN IF NOT EXISTS "verified_by" text;--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "couriers" ADD CONSTRAINT "couriers_verified_by_users_id_fk"
    FOREIGN KEY ("verified_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint

-- Everyone already riding stays on the road. The column defaults to 'pending'
-- so every FUTURE applicant faces a review, but backfilling the existing rows
-- to 'pending' would have taken every working courier off the order flow the
-- moment this migration ran — a deploy-day outage dressed up as a policy. They
-- were vetted by whatever process predates this feature; that's grandfathered,
-- deliberately and once.
UPDATE "couriers" SET "verification_status" = 'approved' WHERE "verification_status" = 'pending';
