CREATE TYPE "public"."offer_state" AS ENUM('offered', 'accepted', 'declined', 'expired', 'superseded');--> statement-breakpoint
CREATE TABLE "order_offers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "order_offers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"order_id" text NOT NULL,
	"courier_id" integer NOT NULL,
	"state" "offer_state" DEFAULT 'offered' NOT NULL,
	"round" integer DEFAULT 1 NOT NULL,
	"offered_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"responded_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "offer_pool_opened_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "order_offers" ADD CONSTRAINT "order_offers_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_offers" ADD CONSTRAINT "order_offers_courier_id_couriers_id_fk" FOREIGN KEY ("courier_id") REFERENCES "public"."couriers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "order_offers_one_live_per_order" ON "order_offers" USING btree ("order_id") WHERE "order_offers"."state" = 'offered';--> statement-breakpoint
CREATE INDEX "order_offers_courier_state_idx" ON "order_offers" USING btree ("courier_id","state");--> statement-breakpoint
CREATE INDEX "order_offers_expiry_idx" ON "order_offers" USING btree ("state","expires_at");