CREATE TABLE "courier_devices" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "courier_devices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"courier_id" integer NOT NULL,
	"fcm_token" text NOT NULL,
	"device_token_hash" text NOT NULL,
	"platform" varchar(20) DEFAULT 'android' NOT NULL,
	"app_version" varchar(30),
	"last_seen_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "courier_devices" ADD CONSTRAINT "courier_devices_courier_id_couriers_id_fk" FOREIGN KEY ("courier_id") REFERENCES "public"."couriers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "courier_devices_fcm_token_uq" ON "courier_devices" USING btree ("fcm_token");--> statement-breakpoint
CREATE UNIQUE INDEX "courier_devices_token_hash_uq" ON "courier_devices" USING btree ("device_token_hash");--> statement-breakpoint
CREATE INDEX "courier_devices_courier_idx" ON "courier_devices" USING btree ("courier_id");