-- Cashier shifts: the stint at the drawer that a closing report reports on.
--
-- Three facts the POS could not state before this table existed: what float the
-- drawer started with, when the stint opened and closed, and whether the money
-- in the drawer at the end matched the money the system expected. The first two
-- were unrecorded; the third was never asked.
--
-- Sales and cash movements are attached by foreign key rather than gathered by
-- a time window, so a shift that closes after midnight still reports as one
-- shift and no clock skew can re-bucket a sale. See db/schema.ts for the rest
-- of the reasoning, including why opening_float is NOT a cashflow row.

CREATE TABLE IF NOT EXISTS "cashier_shifts" (
  "id"            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "outlet_id"     integer NOT NULL,
  "user_id"       text NOT NULL,
  "cashier_name"  varchar(100) NOT NULL,
  "opening_float" numeric(14, 2) DEFAULT '0' NOT NULL,
  "opened_at"     timestamp with time zone DEFAULT now() NOT NULL,
  "closed_at"     timestamp with time zone,
  "counted_cash"  numeric(14, 2),
  "expected_cash" numeric(14, 2),
  "variance"      numeric(14, 2),
  "closing_note"  varchar(255)
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "cashier_shifts" ADD CONSTRAINT "cashier_shifts_outlet_id_outlets_id_fk"
    FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "cashier_shifts" ADD CONSTRAINT "cashier_shifts_user_id_users_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

-- One open shift per outlet. Not a nicety: without it a second "Buka Shift"
-- tap — or a second device at the same counter — splits one drawer's takings
-- across two shifts, and neither of them reconciles against the cash in it.
CREATE UNIQUE INDEX IF NOT EXISTS "cashier_shifts_one_open_per_outlet"
  ON "cashier_shifts" ("outlet_id") WHERE "closed_at" IS NULL;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "cashier_shifts_outlet_opened_idx"
  ON "cashier_shifts" ("outlet_id", "opened_at");
--> statement-breakpoint

-- ── What belongs to a shift ─────────────────────────────────────────────────
-- Both nullable, and both stay nullable. Selling with no shift open is a real
-- state (nobody tapped the button) and money still moves when the counter is
-- closed (the owner settling an invoice from the office). Those rows simply
-- appear on no closing report. Every historical row is one of them, which is
-- why there is no backfill here: inventing a shift for orders that were never
-- rung up under one would fabricate a reconciliation that never happened.

ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "shift_id" integer;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "orders" ADD CONSTRAINT "orders_shift_id_cashier_shifts_id_fk"
    FOREIGN KEY ("shift_id") REFERENCES "public"."cashier_shifts"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "orders_shift_id_idx" ON "orders" ("shift_id");
--> statement-breakpoint

ALTER TABLE "cashFlows" ADD COLUMN IF NOT EXISTS "shift_id" integer;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "cashFlows" ADD CONSTRAINT "cashFlows_shift_id_cashier_shifts_id_fk"
    FOREIGN KEY ("shift_id") REFERENCES "public"."cashier_shifts"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "cash_flows_shift_id_idx" ON "cashFlows" ("shift_id");
