-- Product add-ons ("Topping", "Level Pedas", "Ukuran").
--
-- An add-on is a CHILD ORDER LINE, not a new kind of thing. It is an ordinary
-- product sold alongside a parent line and pointed at it by parent_detail_id.
-- That one decision is what makes the rest of this free:
--
--   * cost      applySaleStockOut is called with the CHILD's order_detail_id,
--               so the ledger tags the add-on's movements to the add-on's own
--               line. cogs.ts already costs per line and needs no change.
--   * stock     a tracked add-on decrements itself; a composition expands its
--               recipe to leaves. Same code path as any other line.
--   * refunds   applyOrderStockReturn replays by order_id, so children come
--               back with their parent. Nothing to teach it.
--   * revenue   summary_price on each row is what THAT product sold for, so a
--               plain sum over the order's lines is still the order total.
--
-- The alternative — an addons table hanging off the line, or a json blob —
-- would have needed its own stock-out, its own cost freeze, and its own
-- cancellation replay: three duplicates of logic this codebase deliberately
-- keeps in one writer (lib/cost.ts postMovement).
--
-- THE INVARIANT, which every reader below depends on:
--   for every row, summary_price is what the customer paid for THAT product
--   and unit_cost/the ledger is what THAT product cost.
-- Never fold an add-on's price into its parent's summary_price. Both would then
-- carry it, revenue would double count, and COGS — which never reads
-- summary_price — would not, so margin would silently improve.

-- ── The dead column ─────────────────────────────────────────────────────────
-- "extra" was declared in 0000 and never written by anything, in any version:
-- every row is NULL. It was the obvious place to put add-ons and it is the
-- wrong one — a json blob cannot be joined for "how many extra telur did we
-- sell", cannot carry a foreign key for the ledger to tag, and cannot be
-- filtered when counting items. Dropped so it can't be reached for later.
ALTER TABLE "orderDetails" DROP COLUMN IF EXISTS "extra";
--> statement-breakpoint

-- ── The parent link ─────────────────────────────────────────────────────────
-- NULL = an ordinary line. Non-NULL = an add-on belonging to that line.
--
-- ON DELETE CASCADE because an add-on cannot outlive the thing it was added to.
-- Only ever one level deep: a child must never itself be a parent (enforced in
-- the write path, not here — a self-referencing depth check in SQL costs more
-- than it protects).
ALTER TABLE "orderDetails" ADD COLUMN IF NOT EXISTS "parent_detail_id" integer;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "orderDetails" ADD CONSTRAINT "order_details_parent_detail_id_fk"
    FOREIGN KEY ("parent_detail_id") REFERENCES "public"."orderDetails"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint

-- Readers split two ways and both need this: "sum the money" walks every row,
-- "count the items" filters to parents. The partial index serves the second,
-- which is the one that runs on every order list.
CREATE INDEX IF NOT EXISTS "order_details_parent_idx" ON "orderDetails" ("parent_detail_id");
--> statement-breakpoint

-- ── The catalogue ───────────────────────────────────────────────────────────
-- A group is one question put to the cashier: "Topping?", "Level pedas?".
-- Groups are per OUTLET, not per product, so "Topping" is defined once and
-- attached to twenty dishes (product_addon_groups below). Renaming it is then
-- one row instead of twenty.
--
-- min_select/max_select encode the rules. min_select >= 1 is what "wajib pilih"
-- means — there is no separate required flag to disagree with it. max_select
-- NULL is unlimited.
--
-- THESE RULES GOVERN COMPOSITION, NEVER SETTLEMENT. They are enforced in the
-- picker when the cashier is choosing. Checkout accepts whatever a tab already
-- holds: a tab parked before the owner tightened a rule must still be able to
-- be paid for. A POS sale must never fail at the counter because a settings
-- page changed while a customer stood there (same reason a missing open shift
-- does not block a sale — see cashier_shifts in db/schema.ts).
CREATE TABLE IF NOT EXISTS "addon_groups" (
  "id"         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "outlet_id"  integer NOT NULL,
  "name"       varchar(60) NOT NULL,
  "min_select" integer DEFAULT 0 NOT NULL,
  "max_select" integer,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "updated_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at" timestamp with time zone
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "addon_groups" ADD CONSTRAINT "addon_groups_outlet_id_outlets_id_fk"
    FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "addon_groups_outlet_idx" ON "addon_groups" ("outlet_id", "sort_order");
--> statement-breakpoint

-- One option = one product the cashier can pick from a group. It is a real
-- products row (is_for_sale = false keeps it out of the POS grid on its own),
-- which is where its stock, recipe, buying_price and avg_cost come from.
--
-- `price` is what the CUSTOMER pays for it, and it lives here rather than on
-- the product because the same telur can be 5.000 on one dish and free on
-- another. 0 is a real, useful value: a free add-on that still consumes stock
-- and still costs money is exactly the case a POS should be able to state.
--
-- deleted_at, and no hard delete once sold: a held tab in a cashier's
-- localStorage may reference this option for days. Resolution reads archived
-- rows too, so removing an option from the menu never blocks payment for a cart
-- that already contains it.
CREATE TABLE IF NOT EXISTS "addon_group_options" (
  "id"         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "group_id"   integer NOT NULL,
  "product_id" text NOT NULL,
  "price"      numeric(14, 2) DEFAULT '0' NOT NULL,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "updated_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at" timestamp with time zone
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "addon_group_options" ADD CONSTRAINT "addon_group_options_group_id_fk"
    FOREIGN KEY ("group_id") REFERENCES "public"."addon_groups"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "addon_group_options" ADD CONSTRAINT "addon_group_options_product_id_fk"
    FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint

-- One live option per product per group. Partial, so archiving an option and
-- adding it back later is allowed — without the WHERE clause a soft-deleted row
-- would block its own replacement forever.
CREATE UNIQUE INDEX IF NOT EXISTS "addon_group_options_group_product_uq"
  ON "addon_group_options" ("group_id", "product_id") WHERE "deleted_at" IS NULL;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "addon_group_options_group_idx" ON "addon_group_options" ("group_id", "sort_order");
--> statement-breakpoint

-- Which questions get asked about which dish. Soft-deleted for the same reason
-- options are: unlinking a group from a product must not strand a held tab.
CREATE TABLE IF NOT EXISTS "product_addon_groups" (
  "id"         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" text NOT NULL,
  "group_id"   integer NOT NULL,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at" timestamp with time zone
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "product_addon_groups" ADD CONSTRAINT "product_addon_groups_product_id_fk"
    FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "product_addon_groups" ADD CONSTRAINT "product_addon_groups_group_id_fk"
    FOREIGN KEY ("group_id") REFERENCES "public"."addon_groups"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "product_addon_groups_uq"
  ON "product_addon_groups" ("product_id", "group_id") WHERE "deleted_at" IS NULL;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "product_addon_groups_product_idx" ON "product_addon_groups" ("product_id", "sort_order");
