-- Membership: the outlet's own customer database, points ledger, tiers and
-- outlet promo codes, plus the Ultimax subscription tier that unlocks it.
-- See the "Membership" section of db/schema.ts for the reasoning.

-- ADD VALUE is safe inside the migrator's transaction as long as the new label
-- is not *used* in the same transaction. Nothing below references 'ultimax';
-- the plan rows come from seed-plans.ts afterwards.
ALTER TYPE "public"."subscription_tier" ADD VALUE IF NOT EXISTS 'ultimax';
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "public"."member_tier" AS ENUM('silver', 'gold', 'platinum', 'diamond');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "public"."point_movement_kind" AS ENUM('earn', 'redeem', 'reversal', 'adjust', 'expire');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "public"."outlet_promo_type" AS ENUM('percent', 'amount');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

-- ── Members ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "outlets_members" (
  "id"             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "outlet_id"      integer NOT NULL,
  "phone"          varchar(20) NOT NULL,
  "name"           varchar(100) NOT NULL,
  "member_code"    varchar(12) NOT NULL,
  "tier"           "public"."member_tier" DEFAULT 'silver' NOT NULL,
  "tier_manual"    boolean DEFAULT false NOT NULL,
  "points_balance" integer DEFAULT 0 NOT NULL,
  "lifetime_spend" numeric(14, 2) DEFAULT '0' NOT NULL,
  "visit_count"    integer DEFAULT 0 NOT NULL,
  "user_id"        text,
  "note"           varchar(255),
  "updated_at"     timestamp with time zone,
  "created_at"     timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at"     timestamp with time zone
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "outlets_members" ADD CONSTRAINT "outlets_members_outlet_id_outlets_id_fk"
    FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "outlets_members" ADD CONSTRAINT "outlets_members_user_id_users_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

-- One live member per phone per outlet. Partial: removal is soft, and a member
-- deleted by mistake and registered again is a normal history.
CREATE UNIQUE INDEX IF NOT EXISTS "outlets_members_outlet_phone_uq"
  ON "outlets_members" ("outlet_id", "phone") WHERE "deleted_at" IS NULL;
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "outlets_members_outlet_code_uq"
  ON "outlets_members" ("outlet_id", "member_code");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "outlets_members_outlet_name_idx"
  ON "outlets_members" ("outlet_id", "name");
--> statement-breakpoint

-- ── Points ledger ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "member_point_movements" (
  "id"            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "member_id"     integer NOT NULL,
  "outlet_id"     integer NOT NULL,
  "order_id"      text,
  "kind"          "public"."point_movement_kind" NOT NULL,
  "delta"         integer NOT NULL,
  "balance_after" integer NOT NULL,
  "note"          varchar(255),
  "actor_user_id" text,
  "created_at"    timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "member_point_movements" ADD CONSTRAINT "member_point_movements_member_id_outlets_members_id_fk"
    FOREIGN KEY ("member_id") REFERENCES "public"."outlets_members"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "member_point_movements" ADD CONSTRAINT "member_point_movements_outlet_id_outlets_id_fk"
    FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "member_point_movements" ADD CONSTRAINT "member_point_movements_order_id_orders_id_fk"
    FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "member_point_movements" ADD CONSTRAINT "member_point_movements_actor_user_id_users_id_fk"
    FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "member_point_movements_member_idx"
  ON "member_point_movements" ("member_id", "created_at");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "member_point_movements_order_idx"
  ON "member_point_movements" ("order_id");
--> statement-breakpoint

-- ── Programme settings + tier table ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "outlet_membership_settings" (
  "outlet_id"           integer PRIMARY KEY NOT NULL,
  "enabled"             boolean DEFAULT false NOT NULL,
  "earn_rp_per_point"   integer DEFAULT 10000 NOT NULL,
  "redeem_rp_per_point" integer DEFAULT 1000 NOT NULL,
  "max_redeem_percent"  integer DEFAULT 100 NOT NULL,
  "min_redeem_points"   integer DEFAULT 1 NOT NULL,
  "updated_at"          timestamp with time zone,
  "created_at"          timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "outlet_membership_settings" ADD CONSTRAINT "outlet_membership_settings_outlet_id_outlets_id_fk"
    FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "outlet_member_tiers" (
  "id"                 integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "outlet_id"          integer NOT NULL,
  "tier"               "public"."member_tier" NOT NULL,
  "earn_multiplier"    numeric(4, 2) DEFAULT '1' NOT NULL,
  "min_lifetime_spend" numeric(14, 2) DEFAULT '0' NOT NULL,
  "updated_at"         timestamp with time zone
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "outlet_member_tiers" ADD CONSTRAINT "outlet_member_tiers_outlet_id_outlets_id_fk"
    FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "outlet_member_tiers_outlet_tier_uq"
  ON "outlet_member_tiers" ("outlet_id", "tier");
--> statement-breakpoint

-- ── Outlet promo codes ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "outlet_promos" (
  "id"               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "outlet_id"        integer NOT NULL,
  "code"             varchar(30) NOT NULL,
  "title"            varchar(100) NOT NULL,
  "discount_type"    "public"."outlet_promo_type" NOT NULL,
  "discount_value"   integer NOT NULL,
  "min_order"        integer DEFAULT 0 NOT NULL,
  "max_discount"     integer,
  "tiers"            text[] DEFAULT '{}' NOT NULL,
  "member_only"      boolean DEFAULT true NOT NULL,
  "valid_from"       timestamp with time zone,
  "valid_until"      timestamp with time zone,
  "usage_limit"      integer,
  "per_member_limit" integer,
  "used_count"       integer DEFAULT 0 NOT NULL,
  "is_active"        boolean DEFAULT true NOT NULL,
  "updated_at"       timestamp with time zone,
  "created_at"       timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at"       timestamp with time zone
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "outlet_promos" ADD CONSTRAINT "outlet_promos_outlet_id_outlets_id_fk"
    FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "outlet_promos_outlet_code_uq"
  ON "outlet_promos" ("outlet_id", "code") WHERE "deleted_at" IS NULL;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "outlet_promo_uses" (
  "id"              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "promo_id"        integer NOT NULL,
  "order_id"        text NOT NULL,
  "member_id"       integer,
  "discount_amount" numeric(14, 2) NOT NULL,
  "created_at"      timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "outlet_promo_uses" ADD CONSTRAINT "outlet_promo_uses_promo_id_outlet_promos_id_fk"
    FOREIGN KEY ("promo_id") REFERENCES "public"."outlet_promos"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "outlet_promo_uses" ADD CONSTRAINT "outlet_promo_uses_order_id_orders_id_fk"
    FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "outlet_promo_uses" ADD CONSTRAINT "outlet_promo_uses_member_id_outlets_members_id_fk"
    FOREIGN KEY ("member_id") REFERENCES "public"."outlets_members"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "outlet_promo_uses_promo_member_idx"
  ON "outlet_promo_uses" ("promo_id", "member_id");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "outlet_promo_uses_order_idx"
  ON "outlet_promo_uses" ("order_id");
--> statement-breakpoint

-- ── What a sale froze ───────────────────────────────────────────────────────
-- All NULL for every existing order and for any sale with no member, promo or
-- points. NULL is not zero: "no member" and "member who earned 0" differ.
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "member_id" integer;
--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "outlet_promo_id" integer;
--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "promo_discount_amount" numeric(14, 2);
--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "points_redeemed" integer;
--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "points_discount_amount" numeric(14, 2);
--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "points_earned" integer;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "orders" ADD CONSTRAINT "orders_member_id_outlets_members_id_fk"
    FOREIGN KEY ("member_id") REFERENCES "public"."outlets_members"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "orders" ADD CONSTRAINT "orders_outlet_promo_id_outlet_promos_id_fk"
    FOREIGN KEY ("outlet_promo_id") REFERENCES "public"."outlet_promos"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "orders_member_id_idx"
  ON "orders" ("member_id") WHERE "member_id" IS NOT NULL;
