-- Table management ("Manajemen Meja"): floor plan zones, tables, seatings and
-- their open bills, reservations and the waiting list.
-- See the "Table management" section of db/schema.ts for the reasoning — above
-- all, why an open bill lives here and not in `orders` until it is paid.
--
-- Written idempotently (IF NOT EXISTS / duplicate_object guards) so a re-run
-- after a journal `when` correction is harmless.

ALTER TABLE "outlets" ADD COLUMN IF NOT EXISTS "table_overtime_minutes" integer DEFAULT 90 NOT NULL;
--> statement-breakpoint

-- ── Zones ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "dining_zones" (
  "id"         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "outlet_id"  integer NOT NULL,
  "name"       varchar(40) NOT NULL,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "walls"      jsonb DEFAULT '[]'::jsonb NOT NULL,
  "updated_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at" timestamp with time zone
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "dining_zones" ADD CONSTRAINT "dining_zones_outlet_id_outlets_id_fk"
    FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "dining_zones_outlet_idx"
  ON "dining_zones" USING btree ("outlet_id", "sort_order") WHERE deleted_at is null;
--> statement-breakpoint

-- ── Seatings ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "table_sessions" (
  "id"                text PRIMARY KEY NOT NULL,
  "outlet_id"         integer NOT NULL,
  "guest_name"        varchar(100),
  "pax"               integer DEFAULT 1 NOT NULL,
  "status"            varchar(12) DEFAULT 'open' NOT NULL,
  "version"           integer DEFAULT 1 NOT NULL,
  "seated_at"         timestamp with time zone DEFAULT now() NOT NULL,
  "bill_requested_at" timestamp with time zone,
  "alert_at"          timestamp with time zone,
  "alert_note"        varchar(100),
  "split_count"       integer,
  "paid_at"           timestamp with time zone,
  "closed_at"         timestamp with time zone,
  "merged_into"       text,
  "opened_by"         text,
  "updated_at"        timestamp with time zone,
  "created_at"        timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at"        timestamp with time zone,
  CONSTRAINT "table_sessions_status_ck"
    CHECK ("status" in ('open', 'paid', 'closed', 'cancelled', 'merged')),
  CONSTRAINT "table_sessions_pax_ck" CHECK ("pax" >= 1)
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "table_sessions" ADD CONSTRAINT "table_sessions_outlet_id_outlets_id_fk"
    FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "table_sessions" ADD CONSTRAINT "table_sessions_merged_into_table_sessions_id_fk"
    FOREIGN KEY ("merged_into") REFERENCES "public"."table_sessions"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "table_sessions" ADD CONSTRAINT "table_sessions_opened_by_users_id_fk"
    FOREIGN KEY ("opened_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "table_sessions_outlet_live_idx"
  ON "table_sessions" USING btree ("outlet_id") WHERE closed_at is null;
--> statement-breakpoint

-- ── Tables ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "dining_tables" (
  "id"             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "outlet_id"      integer NOT NULL,
  "zone_id"        integer NOT NULL,
  "label"          varchar(10) NOT NULL,
  "capacity"       integer DEFAULT 4 NOT NULL,
  "shape"          varchar(10) DEFAULT 'square' NOT NULL,
  "x"              integer NOT NULL,
  "y"              integer NOT NULL,
  "w"              integer NOT NULL,
  "h"              integer NOT NULL,
  "session_id"     text,
  "blocked_at"     timestamp with time zone,
  "blocked_reason" varchar(100),
  "updated_at"     timestamp with time zone,
  "created_at"     timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at"     timestamp with time zone,
  CONSTRAINT "dining_tables_shape_ck" CHECK ("shape" in ('square', 'round')),
  CONSTRAINT "dining_tables_capacity_ck" CHECK ("capacity" >= 1)
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "dining_tables" ADD CONSTRAINT "dining_tables_outlet_id_outlets_id_fk"
    FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "dining_tables" ADD CONSTRAINT "dining_tables_zone_id_dining_zones_id_fk"
    FOREIGN KEY ("zone_id") REFERENCES "public"."dining_zones"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "dining_tables" ADD CONSTRAINT "dining_tables_session_id_table_sessions_id_fk"
    FOREIGN KEY ("session_id") REFERENCES "public"."table_sessions"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "dining_tables_outlet_idx"
  ON "dining_tables" USING btree ("outlet_id") WHERE deleted_at is null;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "dining_tables_session_idx"
  ON "dining_tables" USING btree ("session_id") WHERE session_id is not null;
--> statement-breakpoint

-- ── Open-bill lines ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "table_session_lines" (
  "id"         text PRIMARY KEY NOT NULL,
  "session_id" text NOT NULL,
  "bill_no"    integer DEFAULT 1 NOT NULL,
  "product_id" text NOT NULL,
  "product"    jsonb NOT NULL,
  "quantity"   integer NOT NULL,
  "addons"     jsonb DEFAULT '[]'::jsonb NOT NULL,
  "note"       varchar(200),
  "sent_qty"   integer DEFAULT 0 NOT NULL,
  "order_id"   text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone,
  CONSTRAINT "table_session_lines_qty_ck" CHECK ("quantity" > 0),
  CONSTRAINT "table_session_lines_sent_ck" CHECK ("sent_qty" >= 0),
  CONSTRAINT "table_session_lines_bill_ck" CHECK ("bill_no" >= 1)
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "table_session_lines" ADD CONSTRAINT "table_session_lines_session_id_table_sessions_id_fk"
    FOREIGN KEY ("session_id") REFERENCES "public"."table_sessions"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "table_session_lines" ADD CONSTRAINT "table_session_lines_product_id_products_id_fk"
    FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "table_session_lines" ADD CONSTRAINT "table_session_lines_order_id_orders_id_fk"
    FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "table_session_lines_session_idx"
  ON "table_session_lines" USING btree ("session_id");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "table_session_lines_order_idx"
  ON "table_session_lines" USING btree ("order_id") WHERE order_id is not null;
--> statement-breakpoint

-- ── Reservations ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "table_reservations" (
  "id"          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "outlet_id"   integer NOT NULL,
  "table_id"    integer,
  "guest_name"  varchar(100) NOT NULL,
  "phone"       varchar(20),
  "pax"         integer DEFAULT 2 NOT NULL,
  "reserved_at" timestamp with time zone NOT NULL,
  "note"        varchar(255),
  "status"      varchar(12) DEFAULT 'booked' NOT NULL,
  "session_id"  text,
  "created_by"  text,
  "updated_at"  timestamp with time zone,
  "created_at"  timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at"  timestamp with time zone,
  CONSTRAINT "table_reservations_status_ck"
    CHECK ("status" in ('booked', 'seated', 'cancelled', 'no_show'))
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "table_reservations" ADD CONSTRAINT "table_reservations_outlet_id_outlets_id_fk"
    FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "table_reservations" ADD CONSTRAINT "table_reservations_table_id_dining_tables_id_fk"
    FOREIGN KEY ("table_id") REFERENCES "public"."dining_tables"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "table_reservations" ADD CONSTRAINT "table_reservations_session_id_table_sessions_id_fk"
    FOREIGN KEY ("session_id") REFERENCES "public"."table_sessions"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "table_reservations" ADD CONSTRAINT "table_reservations_created_by_users_id_fk"
    FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "table_reservations_outlet_time_idx"
  ON "table_reservations" USING btree ("outlet_id", "reserved_at");
--> statement-breakpoint

-- ── Waiting list ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "table_waitlist" (
  "id"           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "outlet_id"    integer NOT NULL,
  "queue_no"     integer NOT NULL,
  "guest_name"   varchar(100) NOT NULL,
  "phone"        varchar(20),
  "pax"          integer DEFAULT 2 NOT NULL,
  "note"         varchar(255),
  "called_at"    timestamp with time zone,
  "seated_at"    timestamp with time zone,
  "cancelled_at" timestamp with time zone,
  "session_id"   text,
  "created_at"   timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at"   timestamp with time zone
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "table_waitlist" ADD CONSTRAINT "table_waitlist_outlet_id_outlets_id_fk"
    FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "table_waitlist" ADD CONSTRAINT "table_waitlist_session_id_table_sessions_id_fk"
    FOREIGN KEY ("session_id") REFERENCES "public"."table_sessions"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "table_waitlist_outlet_waiting_idx"
  ON "table_waitlist" USING btree ("outlet_id", "created_at")
  WHERE seated_at is null and cancelled_at is null;
