-- Kitchen Display (KDS): tickets the kitchen works from, and the kitchen's
-- "Recall" — a call for a waiter that shows on the floor page until someone
-- acknowledges it. See the "Kitchen Display" section of db/schema.ts.
--
-- Written idempotently (IF NOT EXISTS / duplicate_object guards) so a re-run
-- after a journal `when` correction is harmless.

CREATE TABLE IF NOT EXISTS "kitchen_tickets" (
  "id"          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "outlet_id"   integer NOT NULL,
  "ticket_no"   integer NOT NULL,
  "source"      varchar(10) NOT NULL,
  "session_id"  text,
  "source_key"  varchar(64),
  "label"       varchar(40),
  "customer"    varchar(100),
  "note"        varchar(255),
  "lines"       jsonb DEFAULT '[]'::jsonb NOT NULL,
  "status"      varchar(12) DEFAULT 'open' NOT NULL,
  "status_at"   timestamp with time zone DEFAULT now() NOT NULL,
  "started_at"  timestamp with time zone,
  "call_at"     timestamp with time zone,
  "call_note"   varchar(100),
  "call_count"  integer DEFAULT 0 NOT NULL,
  "call_ack_at" timestamp with time zone,
  "call_ack_by" text,
  "created_by"  text,
  "created_at"  timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at"  timestamp with time zone,
  CONSTRAINT "kitchen_tickets_source_ck" CHECK ("source" in ('table', 'counter')),
  CONSTRAINT "kitchen_tickets_status_ck"
    CHECK ("status" in ('open', 'in_progress', 'done', 'hold', 'cancelled'))
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "kitchen_tickets" ADD CONSTRAINT "kitchen_tickets_outlet_id_outlets_id_fk"
    FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "kitchen_tickets" ADD CONSTRAINT "kitchen_tickets_session_id_table_sessions_id_fk"
    FOREIGN KEY ("session_id") REFERENCES "public"."table_sessions"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "kitchen_tickets" ADD CONSTRAINT "kitchen_tickets_call_ack_by_users_id_fk"
    FOREIGN KEY ("call_ack_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "kitchen_tickets" ADD CONSTRAINT "kitchen_tickets_created_by_users_id_fk"
    FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "kitchen_tickets_outlet_created_idx"
  ON "kitchen_tickets" USING btree ("outlet_id", "created_at");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "kitchen_tickets_pending_call_idx"
  ON "kitchen_tickets" USING btree ("outlet_id") WHERE call_at is not null and call_ack_at is null;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "kitchen_tickets_source_key_idx"
  ON "kitchen_tickets" USING btree ("outlet_id", "source_key") WHERE source_key is not null;
