-- Stock opname SESSIONS: a physical count that may take days while the shop
-- keeps selling. See the "Stock opname SESSIONS" section of db/schema.ts.
--
-- Each counted line keeps the time it was counted and is compared with the
-- system stock at that moment (current stock minus every movement after it),
-- so a sale made in the middle of a two-day count is not booked as shrinkage.
-- The adjustments post only when the session is finished, dated at each
-- line's counted_at.
--
-- Written idempotently (IF NOT EXISTS / duplicate_object guards) so a re-run
-- after a journal `when` correction is harmless.

CREATE TABLE IF NOT EXISTS "stock_opname_sessions" (
  "id"          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "outlet_id"   integer NOT NULL,
  "note"        varchar(255) DEFAULT '' NOT NULL,
  "status"      varchar(12) DEFAULT 'open' NOT NULL,
  "started_at"  timestamp with time zone DEFAULT now() NOT NULL,
  "started_by"  text,
  "finished_at" timestamp with time zone,
  "finished_by" text,
  CONSTRAINT "stock_opname_sessions_status_ck" CHECK ("status" in ('open', 'finished', 'cancelled'))
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "stock_opname_lines" (
  "id"         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "session_id" integer NOT NULL,
  "product_id" text NOT NULL,
  "counted"    numeric(12, 3) NOT NULL,
  "counted_at" timestamp with time zone NOT NULL,
  "counted_by" text,
  "unit_cost"  numeric(14, 4),
  "system_qty" numeric(12, 3),
  "delta"      numeric(12, 3),
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "stock_opname_sessions" ADD CONSTRAINT "stock_opname_sessions_outlet_id_outlets_id_fk"
    FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "stock_opname_sessions" ADD CONSTRAINT "stock_opname_sessions_started_by_users_id_fk"
    FOREIGN KEY ("started_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "stock_opname_sessions" ADD CONSTRAINT "stock_opname_sessions_finished_by_users_id_fk"
    FOREIGN KEY ("finished_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "stock_opname_lines" ADD CONSTRAINT "stock_opname_lines_session_id_stock_opname_sessions_id_fk"
    FOREIGN KEY ("session_id") REFERENCES "public"."stock_opname_sessions"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "stock_opname_lines" ADD CONSTRAINT "stock_opname_lines_product_id_products_id_fk"
    FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "stock_opname_lines" ADD CONSTRAINT "stock_opname_lines_counted_by_users_id_fk"
    FOREIGN KEY ("counted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

-- One open session per outlet: two counts running side by side would each
-- compare against a stock the other is about to change.
CREATE UNIQUE INDEX IF NOT EXISTS "stock_opname_sessions_one_open_idx"
  ON "stock_opname_sessions" USING btree ("outlet_id") WHERE status = 'open';
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "stock_opname_sessions_outlet_started_idx"
  ON "stock_opname_sessions" USING btree ("outlet_id", "started_at");
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "stock_opname_lines_session_product_idx"
  ON "stock_opname_lines" USING btree ("session_id", "product_id");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "stock_opname_lines_product_counted_idx"
  ON "stock_opname_lines" USING btree ("product_id", "counted_at");
--> statement-breakpoint

-- "Stock at time T" sums a product's movements after T; without this every
-- lookup reads the product's whole history.
CREATE INDEX IF NOT EXISTS "stock_movements_product_created_idx"
  ON "stock_movements" USING btree ("product_id", "created_at");
