-- How an outlet's customer receipt (struk) is printed: the owner's own header
-- and footer notes, a QR link, and a show/hide switch for each optional line.
-- See the "Receipt (struk) print settings" section of db/schema.ts.
--
-- One row per outlet, written the first time the owner saves the settings. No
-- row means the default receipt, so nothing is backfilled and every existing
-- outlet keeps printing exactly what it prints today.
--
-- Written idempotently so a re-run after a journal `when` correction is
-- harmless.

CREATE TABLE IF NOT EXISTS "outlet_printer_settings" (
  "id"                integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "outlet_id"         integer NOT NULL,
  "header_note"       text,
  "footer_note"       text,
  "qr_url"            text,
  "qr_caption"        varchar(40),
  "show_logo"         boolean DEFAULT true NOT NULL,
  "show_outlet_name"  boolean DEFAULT true NOT NULL,
  "show_address"      boolean DEFAULT true NOT NULL,
  "show_phone"        boolean DEFAULT true NOT NULL,
  "show_cashier"      boolean DEFAULT true NOT NULL,
  "show_customer"     boolean DEFAULT true NOT NULL,
  "show_pager"        boolean DEFAULT true NOT NULL,
  "show_table"        boolean DEFAULT true NOT NULL,
  "show_service_type" boolean DEFAULT true NOT NULL,
  "show_member"       boolean DEFAULT true NOT NULL,
  "show_savings"      boolean DEFAULT true NOT NULL,
  "show_header_note"  boolean DEFAULT true NOT NULL,
  "show_footer_note"  boolean DEFAULT true NOT NULL,
  "show_qr"           boolean DEFAULT true NOT NULL,
  "created_at"        timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at"        timestamp with time zone
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "outlet_printer_settings" ADD CONSTRAINT "outlet_printer_settings_outlet_id_outlets_id_fk"
    FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "outlet_printer_settings_outlet_idx" ON "outlet_printer_settings" USING btree ("outlet_id");
