-- Every slip printed BEFORE the money is booked, and the owner's switch for the
-- cashier's pre-checkout struk button.
--
-- A cashier can ring up a cart, print the customer's struk from the button
-- beside Checkout, take the cash and never press Checkout — and a slip is only
-- paper, so nothing of that sale ever reached the server. print_logs is that
-- missing trace: one row per press of Cetak on a slip that asks to be paid
-- (the cashier's pre-checkout struk, a table's "Cetak Bill" in Manajemen Meja),
-- with what it listed and the total it asked for. When the sale is checked out
-- the row gains its order_id, so a row still without one is a slip that was
-- handed over and never paid. See the "Print logs" section of db/schema.ts.
--
-- outlets.precheckout_receipt_enabled: TRUE by default so every existing
-- outlet keeps the button it has today. Off hides it; Checkout still prints the
-- receipt as it always has.
--
-- Written idempotently so a re-run after a journal `when` correction is
-- harmless.

ALTER TABLE "outlets" ADD COLUMN IF NOT EXISTS "precheckout_receipt_enabled" boolean DEFAULT true NOT NULL;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "print_logs" (
  "id"          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "outlet_id"   integer NOT NULL,
  "kind"        varchar(12) NOT NULL,
  "source_key"  varchar(64),
  "session_id"  text,
  "bill_no"     integer,
  "label"       varchar(40),
  "customer"    varchar(100),
  "lines"       jsonb DEFAULT '[]'::jsonb NOT NULL,
  "total"       numeric(14, 2) NOT NULL,
  "order_id"    text,
  "created_by"  text,
  "created_at"  timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at"  timestamp with time zone,
  CONSTRAINT "print_logs_kind_ck" CHECK ("kind" in ('receipt', 'table_bill'))
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "print_logs" ADD CONSTRAINT "print_logs_outlet_id_outlets_id_fk"
    FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "print_logs" ADD CONSTRAINT "print_logs_session_id_table_sessions_id_fk"
    FOREIGN KEY ("session_id") REFERENCES "public"."table_sessions"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "print_logs" ADD CONSTRAINT "print_logs_order_id_orders_id_fk"
    FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "print_logs" ADD CONSTRAINT "print_logs_created_by_users_id_fk"
    FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "print_logs_outlet_created_idx" ON "print_logs" USING btree ("outlet_id", "created_at");
--> statement-breakpoint

-- What checkout searches, and what an audit lists: the slips not yet paid.
CREATE INDEX IF NOT EXISTS "print_logs_unpaid_idx" ON "print_logs" USING btree ("outlet_id", "source_key") WHERE "order_id" IS NULL;
