-- Pesan Mandiri on the till app: the phones to ring with an FCM push when a
-- customer sends an order, so a till whose app is closed still rings. See
-- staffDevicesTable in db/schema.ts.
--
-- Nothing is backfilled: a phone appears here once the app registers it.
--
-- Written idempotently so a re-run after a journal `when` correction is
-- harmless.

CREATE TABLE IF NOT EXISTS "staff_devices" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" text NOT NULL REFERENCES "users"("id") ON DELETE cascade,
  "outlet_id" integer NOT NULL REFERENCES "outlets"("id") ON DELETE cascade,
  "fcm_token" text NOT NULL,
  "platform" varchar(20) DEFAULT 'android' NOT NULL,
  "app_version" varchar(30),
  "last_seen_at" timestamp with time zone,
  "revoked_at" timestamp with time zone,
  "updated_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "staff_devices_fcm_token_uq" ON "staff_devices" USING btree ("fcm_token");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "staff_devices_outlet_idx" ON "staff_devices" USING btree ("outlet_id") WHERE revoked_at is null;
