-- Admin protection, part 2: the admin activity log, the browsers each admin
-- has signed in from (new-browser email alert), and per-session password
-- re-check state for risky admin actions. See lib/admin-activity.ts,
-- lib/admin-devices.ts and lib/admin-access.ts.
--
-- Written idempotently so a re-run after a journal `when` correction is
-- harmless.

CREATE TABLE IF NOT EXISTS "admin_activity_log" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "admin_user_id" text REFERENCES "users"("id") ON DELETE set null,
  "admin_email" varchar(255),
  "action" varchar(160) NOT NULL,
  "target" varchar(255),
  "detail" jsonb,
  "status_code" integer,
  "ip_address" text,
  "user_agent" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "admin_activity_created_idx" ON "admin_activity_log" USING btree ("created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "admin_activity_admin_idx" ON "admin_activity_log" USING btree ("admin_user_id");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "admin_devices" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" text NOT NULL REFERENCES "users"("id") ON DELETE cascade,
  "device_hash" text NOT NULL,
  "user_agent" text,
  "ip_address" text,
  "first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
  "last_seen_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "admin_devices_user_device_uq" ON "admin_devices" USING btree ("user_id", "device_hash");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "admin_step_up" (
  "session_id" text PRIMARY KEY NOT NULL REFERENCES "session"("id") ON DELETE cascade,
  "confirmed_at" timestamp with time zone,
  "failed_count" integer DEFAULT 0 NOT NULL,
  "locked_until" timestamp with time zone
);
